### PR TITLE
[add] Croatia rrif CoA initial commit

### PR DESCRIPTION
**Pull request by badbole**
Adds a Croatia chart of accounts

### CODE REVIEW

**Comment by badbole** [comment]
@sbidoul @pedrobaeza  Guys , could i have a bit of help on this PR:
the error i get is related to double usage of same xml-id, 
but i need it twice for the CoA module... 

what would be correct approach to resolve this problem?

**Comment by pedrobaeza** [comment]
Add pylint ignore clauses in the conflicting lines.

**Comment by badbole** [comment]
> Add pylint ignore clauses in the conflicting lines.

Thnx, but... not sure if i know the procedure.. 
could you help with a hint/link/example please?

**Comment by badbole** [comment]
> Add pylint ignore clauses in the conflicting lines.

GR8!! TNX For tip!... works fine

**Comment by badbole** [comment]
@gkliska can i get opinion oon this PR? asap would be nice?

**Pull request closed without merging**
